package com.cn.hnust.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.cn.hnust.pojo.joke.Joke;
import com.cn.hnust.pojo.joke.JokeExample;

@Repository
public interface IJokeDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int countByExample(JokeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int deleteByExample(JokeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int insert(Joke record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int insertSelective(Joke record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	List<Joke> selectByExample(JokeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	Joke selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Joke record, @Param("example") JokeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int updateByExample(@Param("record") Joke record, @Param("example") JokeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int updateByPrimaryKeySelective(Joke record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table joke
	 * @mbggenerated  Sun Feb 12 00:36:31 CST 2017
	 */
	int updateByPrimaryKey(Joke record);
	
	Joke getRandJoke();
}